version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - xpack.security.enabled=false
      - http.max_content_length=2000mb
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app/
      - ./ml/model/:/app/ml/model/
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge
