version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms8g -Xmx8g
      - xpack.security.enabled=false
      - http.max_content_length=2000mb
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Mapping external port 9201 to internal port 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.13.4
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic      

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge